// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package TLogin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//请求注册接口
type ReqRegister struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRegister) Reset()         { *m = ReqRegister{} }
func (m *ReqRegister) String() string { return proto.CompactTextString(m) }
func (*ReqRegister) ProtoMessage()    {}
func (*ReqRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *ReqRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegister.Unmarshal(m, b)
}
func (m *ReqRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegister.Marshal(b, m, deterministic)
}
func (m *ReqRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegister.Merge(m, src)
}
func (m *ReqRegister) XXX_Size() int {
	return xxx_messageInfo_ReqRegister.Size(m)
}
func (m *ReqRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegister proto.InternalMessageInfo

func (m *ReqRegister) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ReqRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//回应注册接口
type AckRegister struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckRegister) Reset()         { *m = AckRegister{} }
func (m *AckRegister) String() string { return proto.CompactTextString(m) }
func (*AckRegister) ProtoMessage()    {}
func (*AckRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *AckRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRegister.Unmarshal(m, b)
}
func (m *AckRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRegister.Marshal(b, m, deterministic)
}
func (m *AckRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRegister.Merge(m, src)
}
func (m *AckRegister) XXX_Size() int {
	return xxx_messageInfo_AckRegister.Size(m)
}
func (m *AckRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRegister.DiscardUnknown(m)
}

var xxx_messageInfo_AckRegister proto.InternalMessageInfo

func (m *AckRegister) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AckRegister) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AckRegister) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//请求登录接口
type ReqLogin struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ReqLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//回应登录接口
type AckLogin struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Uid                  uint32   `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckLogin) Reset()         { *m = AckLogin{} }
func (m *AckLogin) String() string { return proto.CompactTextString(m) }
func (*AckLogin) ProtoMessage()    {}
func (*AckLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *AckLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckLogin.Unmarshal(m, b)
}
func (m *AckLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckLogin.Marshal(b, m, deterministic)
}
func (m *AckLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckLogin.Merge(m, src)
}
func (m *AckLogin) XXX_Size() int {
	return xxx_messageInfo_AckLogin.Size(m)
}
func (m *AckLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_AckLogin.DiscardUnknown(m)
}

var xxx_messageInfo_AckLogin proto.InternalMessageInfo

func (m *AckLogin) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AckLogin) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AckLogin) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AckLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//错误消息
type KickMsg struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickMsg) Reset()         { *m = KickMsg{} }
func (m *KickMsg) String() string { return proto.CompactTextString(m) }
func (*KickMsg) ProtoMessage()    {}
func (*KickMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *KickMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickMsg.Unmarshal(m, b)
}
func (m *KickMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickMsg.Marshal(b, m, deterministic)
}
func (m *KickMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickMsg.Merge(m, src)
}
func (m *KickMsg) XXX_Size() int {
	return xxx_messageInfo_KickMsg.Size(m)
}
func (m *KickMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KickMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KickMsg proto.InternalMessageInfo

func (m *KickMsg) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *KickMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

//错误消息
type ErrorMsg struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorMsg) Reset()         { *m = ErrorMsg{} }
func (m *ErrorMsg) String() string { return proto.CompactTextString(m) }
func (*ErrorMsg) ProtoMessage()    {}
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *ErrorMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorMsg.Unmarshal(m, b)
}
func (m *ErrorMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorMsg.Marshal(b, m, deterministic)
}
func (m *ErrorMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorMsg.Merge(m, src)
}
func (m *ErrorMsg) XXX_Size() int {
	return xxx_messageInfo_ErrorMsg.Size(m)
}
func (m *ErrorMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorMsg proto.InternalMessageInfo

func (m *ErrorMsg) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ErrorMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqRegister)(nil), "TLogin.ReqRegister")
	proto.RegisterType((*AckRegister)(nil), "TLogin.AckRegister")
	proto.RegisterType((*ReqLogin)(nil), "TLogin.ReqLogin")
	proto.RegisterType((*AckLogin)(nil), "TLogin.AckLogin")
	proto.RegisterType((*KickMsg)(nil), "TLogin.KickMsg")
	proto.RegisterType((*ErrorMsg)(nil), "TLogin.ErrorMsg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x0b, 0xf1, 0xc9, 0x4f, 0xcf, 0xcc, 0x53, 0x72, 0xe6,
	0xe2, 0x0e, 0x4a, 0x2d, 0x0c, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49, 0x2d, 0x12, 0x92, 0xe0, 0x62,
	0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x85, 0xa4, 0xb8, 0x38, 0x0a, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x98, 0xc0, 0x52,
	0x70, 0xbe, 0x92, 0x27, 0x17, 0xb7, 0x63, 0x72, 0x36, 0xdc, 0x10, 0x21, 0x2e, 0x96, 0xe4, 0xfc,
	0x94, 0x54, 0xb0, 0x09, 0xbc, 0x41, 0x60, 0xb6, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0x3a, 0x54,
	0x27, 0x88, 0x29, 0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x9f, 0x9d, 0x9a, 0x27, 0xc1, 0x0c, 0x16, 0x83,
	0x70, 0x94, 0x1c, 0xb8, 0x38, 0x82, 0x52, 0x0b, 0xc1, 0x6e, 0x23, 0xd3, 0x31, 0x11, 0x5c, 0x1c,
	0x8e, 0xc9, 0xd9, 0x10, 0x13, 0x70, 0xb8, 0xa4, 0x34, 0x13, 0xa2, 0x8d, 0x37, 0x08, 0xc4, 0x84,
	0xb9, 0x8d, 0x19, 0x8b, 0xdb, 0x58, 0x90, 0xdd, 0xa6, 0xcf, 0xc5, 0xee, 0x9d, 0x99, 0x9c, 0xed,
	0x5b, 0x9c, 0x8e, 0xcf, 0x8b, 0x08, 0x63, 0x94, 0x0c, 0xb8, 0x38, 0x5c, 0x8b, 0x8a, 0xf2, 0x8b,
	0x88, 0xd6, 0x91, 0xc4, 0x06, 0x8e, 0x1d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x0b,
	0xed, 0x4f, 0xaa, 0x01, 0x00, 0x00,
}
